version: '3'
services:
  app1:
    build: ./app1
    container_name: app1
    restart: unless-stopped
    ports:
        - '3000:3000'
  app2:
    build: ./app2
    container_name: app2
    restart: unless-stopped
    ports:
        - '3001:3001'
  app:
    build: ./app
    container_name: app
    restart: unless-stopped
    ports:
        - '3002:3002'
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./app:/var/www/app:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always